Repository ucsb-cs156-s24/proj-gauchoride-s24-5pm-7, pull requests merged in 2024-05, with the labels that each got.

#18 KL-DriversControllerBug
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriversController.java
Labels: 5

#21 bug fix for pickup and dropoff
  frontend/src/main/components/Ride/RideForm.js
Labels: FIXME-See CR

#53 Kate commit info feature
  Dockerfile
  pom.xml
  src/main/java/edu/ucsb/cs156/gauchoride/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/gauchoride/services/SystemInfoServiceImpl.java
  src/test/java/edu/ucsb/cs156/gauchoride/services/SystemInfoServiceImplTests.java
Labels: 10
